2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_setup.py:_flush():69] setting env: {}
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_105130-1nitxf4p/logs/debug.log
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_105130-1nitxf4p/logs/debug-internal.log
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_init.py:init():375] calling init triggers
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-29 10:51:30,611 INFO    MainThread:46146 [wandb_init.py:init():424] starting backend
2021-08-29 10:51:30,611 INFO    MainThread:46146 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-29 10:51:30,623 INFO    MainThread:46146 [backend.py:ensure_launched():135] starting backend process...
2021-08-29 10:51:30,631 INFO    MainThread:46146 [backend.py:ensure_launched():139] started backend process with pid: 46169
2021-08-29 10:51:30,632 INFO    MainThread:46146 [wandb_init.py:init():429] backend started and connected
2021-08-29 10:51:30,633 INFO    MainThread:46146 [wandb_init.py:init():477] updated telemetry
2021-08-29 10:51:30,633 INFO    MainThread:46146 [wandb_init.py:init():500] communicating current version
2021-08-29 10:51:31,384 INFO    MainThread:46146 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-29 10:51:31,385 INFO    MainThread:46146 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-29 10:51:31,600 INFO    MainThread:46146 [wandb_init.py:init():540] starting run threads in backend
2021-08-29 10:51:36,605 INFO    MainThread:46146 [wandb_run.py:_console_start():1584] atexit reg
2021-08-29 10:51:36,605 INFO    MainThread:46146 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-08-29 10:51:36,605 INFO    MainThread:46146 [wandb_run.py:_redirect():1463] Redirecting console.
2021-08-29 10:51:36,609 INFO    MainThread:46146 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-29 10:51:36,609 INFO    MainThread:46146 [wandb_init.py:init():565] run started, returning control to user process
2021-08-29 10:51:39,847 INFO    MainThread:46146 [wandb_watch.py:watch():43] Watching
2021-08-29 10:51:39,850 INFO    MainThread:46146 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-08-29 10:51:39,851 INFO    MainThread:46146 [wandb_run.py:_restore():1526] restore
2021-08-29 10:51:42,224 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:51:42,463 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:51:42,618 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 7880
}

2021-08-29 10:51:42,719 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10880
}

2021-08-29 10:51:42,826 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10880
}

2021-08-29 10:51:42,928 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10880
}

2021-08-29 10:51:43,030 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,131 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,236 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,337 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,439 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,840 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:43,942 INFO    MainThread:46146 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10880
  total_bytes: 10880
}

2021-08-29 10:51:45,065 INFO    MainThread:46146 [wandb_run.py:_show_files():1898] logging synced files
