2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_setup.py:_flush():69] setting env: {}
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_102734-xvfi6rvi/logs/debug.log
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/code/image-classification-level1-22/T2037/wandb/run-20210829_102734-xvfi6rvi/logs/debug-internal.log
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_init.py:init():375] calling init triggers
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-29 10:27:34,242 INFO    MainThread:42278 [wandb_init.py:init():424] starting backend
2021-08-29 10:27:34,243 INFO    MainThread:42278 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-29 10:27:34,254 INFO    MainThread:42278 [backend.py:ensure_launched():135] starting backend process...
2021-08-29 10:27:34,265 INFO    MainThread:42278 [backend.py:ensure_launched():139] started backend process with pid: 42298
2021-08-29 10:27:34,266 INFO    MainThread:42278 [wandb_init.py:init():429] backend started and connected
2021-08-29 10:27:34,267 INFO    MainThread:42278 [wandb_init.py:init():477] updated telemetry
2021-08-29 10:27:34,267 INFO    MainThread:42278 [wandb_init.py:init():500] communicating current version
2021-08-29 10:27:35,026 INFO    MainThread:42278 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-08-29 10:27:35,027 INFO    MainThread:42278 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-29 10:27:35,273 INFO    MainThread:42278 [wandb_init.py:init():540] starting run threads in backend
2021-08-29 10:27:40,277 INFO    MainThread:42278 [wandb_run.py:_console_start():1584] atexit reg
2021-08-29 10:27:40,277 INFO    MainThread:42278 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-08-29 10:27:40,278 INFO    MainThread:42278 [wandb_run.py:_redirect():1463] Redirecting console.
2021-08-29 10:27:40,281 INFO    MainThread:42278 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-29 10:27:40,281 INFO    MainThread:42278 [wandb_init.py:init():565] run started, returning control to user process
2021-08-29 10:27:43,485 INFO    MainThread:42278 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-08-29 10:27:43,485 INFO    MainThread:42278 [wandb_run.py:_restore():1526] restore
2021-08-29 10:27:45,879 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:27:46,100 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 947
}

2021-08-29 10:27:46,286 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 6680
}

2021-08-29 10:27:46,388 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10844
}

2021-08-29 10:27:46,490 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10844
}

2021-08-29 10:27:46,592 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 947
  total_bytes: 10844
}

2021-08-29 10:27:46,694 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:46,796 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:46,899 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:47,001 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:47,103 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:47,488 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:47,589 INFO    MainThread:42278 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10844
  total_bytes: 10844
}

2021-08-29 10:27:48,719 INFO    MainThread:42278 [wandb_run.py:_show_files():1898] logging synced files
